### ISSUE TITLE
Please add diagnostic_event, fault_indication, ch_active and dhw_active

### ISSUE THREAD

**Issue by Mio3000** [sakrut/ESPHome-OpenTherm-Gateway#1]
hello @sakrut, created the issue as requested.

thank you, it looks good, and it would be possible also add diagnostic_event and fault_indication? and also ch_active with dhw_active? just as binary sensors
or i can add them somehow here:

binary_sensor:
  - platform: custom
    lambda: |-
      OpenthermComponent *openthermComp = (OpenthermComponent*) id(opentherm);
      return {openthermComp->flame};
    binary_sensors:
    - name: "Flame"
      #device_class: heat

Thank you

**Comment by sakrut** [comment]
Done. 
you have to download new version of esphome-opentherm/opentherm_component.h 
don't forgot to replace your configuration like [here](https://github.com/sakrut/ESPHome-OpenTherm-Gateway/commit/98ecce19ed5c631b34ad3bbeec27231d098aae4a#diff-e97956ed069305e7690829a9d8282fee213c0bd18de2aed632a6e154e02a8e90), install and reload entity

**Comment by sakrut** [comment]
![image](https://github.com/sakrut/ESPHome-OpenTherm-Gateway/assets/25841934/0080267d-c43a-473d-a414-0899ca319822)
