### ISSUE TITLE
Nie mogę się połączyć z Piecem

### ISSUE THREAD

**Issue by kmarek1** [sakrut/ESPHome-OpenTherm-Gateway#2]
Nie mogę się połączyć z piecem z komunikacją Openterm 
{I cannot connect to a gas furnace with Opentherm communication}
Z tym https://github.com/rsciriano/ESPHome-OpenTherm
I konfiguracji
```
// Pins to OpenTherm Adapter
int inPin = D2; 
int outPin = D1;
OpenTherm ot(inPin, outPin, false);
```
Działa dobrze. 
{Works well.}

Natomiast  (Whereas) [ESPHome-OpenTherm-Gateway](https://github.com/sakrut/ESPHome-OpenTherm-Gateway)
```
// Pins to OpenTherm Adapter
int inPin = 4; 
int outPin = 5;
int sInPin = 12; 
int sOutPin = 13;

OpenTherm ot(inPin, outPin, false);
OpenTherm sOT(sInPin, sOutPin, true);
```
Nie działa wcale
{It doesn't work at all}
Korzystam z adaptera  [Ihor Melnyk](http://ihormelnyk.com/opentherm_adapter),
Schemat podłączenia 
(https://ihormelnyk.com/Content/Pages/opentherm_adapter/opentherm_adapter_esp8266_connection.png)
 
Jakieś rozwiązanie ? 
{Any solution ?}

**Comment by sakrut** [comment]
Twój adapter jest przygotowany tylko master shieldem do komunikacji z boilerem. 
Rozbudowana płytka pod esp to https://diyless.com/product/master-opentherm-shield 
jeśli pinout  odpowiada twojej płytce powinieneś przy nim pozostać.
```
int inPin = D2; 
int outPin = D1;
```

Pinout podany w tym repo odpowiada temu zestawowi: https://diyless.com/product/esp8266-opentherm-gateway

**Comment by kmarek1** [comment]
Dzięki za odpowiedź
Problem w tym że z ESPHome-OpenTherm-Gateway

 przy ustawieniu 
```
int inPin = D2; 
int outPin = D1;
```
Też nie działa.

**Comment by sakrut** [comment]
Ponieważ gateway próbuje się połączyć z boilerem jak i sterownikiem. 
Podany przez ciebie adapter nie obsługuje komunikacji z sterownikiem.

**Comment by sakrut** [comment]
Tu jest adapter pod Andino który będzie kompatybilny. https://diyless.com/product/arduino-opentherm-gateway
